//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IES_2.Res {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IES_2.Res.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AC Relay.
        /// </summary>
        internal static string ACrelay {
            get {
                return ResourceManager.GetString("ACrelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [A].
        /// </summary>
        internal static string Act {
            get {
                return ResourceManager.GetString("Act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AC Gain Parameter (med. load).
        /// </summary>
        internal static string ADGAIN {
            get {
                return ResourceManager.GetString("ADGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ADJUSTING: {0}....
        /// </summary>
        internal static string Adjusting {
            get {
                return ResourceManager.GetString("Adjusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AC Offset Parameter (min. load).
        /// </summary>
        internal static string ADOFFPL {
            get {
                return ResourceManager.GetString("ADOFFPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AC Offset Parameter (min. load, EVAP on).
        /// </summary>
        internal static string ADOFFPURG {
            get {
                return ResourceManager.GetString("ADOFFPURG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AC Offset Parameter (min. load, EVAP off).
        /// </summary>
        internal static string ADOFFSET {
            get {
                return ResourceManager.GetString("ADOFFSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stepper Correction from FLT.
        /// </summary>
        internal static string ALFAFTR {
            get {
                return ResourceManager.GetString("ALFAFTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Stepper Motor Position.
        /// </summary>
        internal static string ALFAR {
            get {
                return ResourceManager.GetString("ALFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Correction.
        /// </summary>
        internal static string ALFAU {
            get {
                return ResourceManager.GetString("ALFAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Correction with A/C.
        /// </summary>
        internal static string ALFAUC {
            get {
                return ResourceManager.GetString("ALFAUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Throttle Opening Angle.
        /// </summary>
        internal static string ANG_PAP0 {
            get {
                return ResourceManager.GetString("ANG_PAP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Above MAX.
        /// </summary>
        internal static string AtMAX {
            get {
                return ResourceManager.GetString("AtMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Below MIN.
        /// </summary>
        internal static string AtMIN {
            get {
                return ResourceManager.GetString("AtMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic Detection.
        /// </summary>
        internal static string autodetect {
            get {
                return ResourceManager.GetString("autodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignition Advance.
        /// </summary>
        internal static string AVANCE {
            get {
                return ResourceManager.GetString("AVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CANCELLED.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clearing error codes....
        /// </summary>
        internal static string ClearingErrors {
            get {
                return ResourceManager.GetString("ClearingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1.
        /// </summary>
        internal static string Coil1 {
            get {
                return ResourceManager.GetString("Coil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2.
        /// </summary>
        internal static string Coil2 {
            get {
                return ResourceManager.GetString("Coil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No ECU Response.
        /// </summary>
        internal static string CommLost {
            get {
                return ResourceManager.GetString("CommLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Interface port ERROR.
        /// </summary>
        internal static string COMnotValid {
            get {
                return ResourceManager.GetString("COMnotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error has occured while openenig the {0} port..
        /// </summary>
        internal static string COMopenError {
            get {
                return ResourceManager.GetString("COMopenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consumption Meter.
        /// </summary>
        internal static string ConMeter {
            get {
                return ResourceManager.GetString("ConMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONNECTED TO:.
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please turn ON the ignition....
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Engine Speed.
        /// </summary>
        internal static string CONS_REG {
            get {
                return ResourceManager.GetString("CONS_REG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stepper Correction (Delta).
        /// </summary>
        internal static string DELREG {
            get {
                return ResourceManager.GetString("DELREG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EGR Valve.
        /// </summary>
        internal static string EGR {
            get {
                return ResourceManager.GetString("EGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please ensure the ignition is ON and engine is STOPPED..
        /// </summary>
        internal static string EnsureIgnOnEngStop {
            get {
                return ResourceManager.GetString("EnsureIgnOnEngStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocallibration Parameter.
        /// </summary>
        internal static string ErrACParam {
            get {
                return ResourceManager.GetString("ErrACParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Air Conditioner.
        /// </summary>
        internal static string ErrAirCo {
            get {
                return ResourceManager.GetString("ErrAirCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic Transmission.
        /// </summary>
        internal static string ErrAutoTrans {
            get {
                return ResourceManager.GetString("ErrAutoTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backdoor Acivated.
        /// </summary>
        internal static string ErrBackdoor {
            get {
                return ResourceManager.GetString("ErrBackdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Battery Voltage.
        /// </summary>
        internal static string ErrBattV {
            get {
                return ResourceManager.GetString("ErrBattV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown CODE ERROR (4).
        /// </summary>
        internal static string ErrC4 {
            get {
                return ResourceManager.GetString("ErrC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cam sensor.
        /// </summary>
        internal static string ErrCam {
            get {
                return ResourceManager.GetString("ErrCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error Counter.
        /// </summary>
        internal static string ErrCnt {
            get {
                return ResourceManager.GetString("ErrCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignition Coil 1.
        /// </summary>
        internal static string ErrCoil1 {
            get {
                return ResourceManager.GetString("ErrCoil1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignition Coil 2.
        /// </summary>
        internal static string ErrCoil2 {
            get {
                return ResourceManager.GetString("ErrCoil2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consumption Meter.
        /// </summary>
        internal static string ErrConMet {
            get {
                return ResourceManager.GetString("ErrConMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CPU.
        /// </summary>
        internal static string ErrCPU {
            get {
                return ResourceManager.GetString("ErrCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Digimatic signal.
        /// </summary>
        internal static string ErrDigimatic {
            get {
                return ResourceManager.GetString("ErrDigimatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Water Temperature Sensor.
        /// </summary>
        internal static string ErrECT {
            get {
                return ResourceManager.GetString("ErrECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EEPROM.
        /// </summary>
        internal static string ErrEEPROM {
            get {
                return ResourceManager.GetString("ErrEEPROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EGR Control.
        /// </summary>
        internal static string ErrEGRCtrl {
            get {
                return ResourceManager.GetString("ErrEGRCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EGR Valve.
        /// </summary>
        internal static string ErrEGRVal {
            get {
                return ResourceManager.GetString("ErrEGRVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EPROM.
        /// </summary>
        internal static string ErrEPROM {
            get {
                return ResourceManager.GetString("ErrEPROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EVAP Valve.
        /// </summary>
        internal static string ErrEVAP {
            get {
                return ResourceManager.GetString("ErrEVAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown FUNC ERROR (7).
        /// </summary>
        internal static string ErrF7 {
            get {
                return ResourceManager.GetString("ErrF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown FUNC ERROR (8).
        /// </summary>
        internal static string ErrF8 {
            get {
                return ResourceManager.GetString("ErrF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fuel Pump.
        /// </summary>
        internal static string ErrFuelPump {
            get {
                return ResourceManager.GetString("ErrFuelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generic System Relay.
        /// </summary>
        internal static string ErrGenRel {
            get {
                return ResourceManager.GetString("ErrGenRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown INPUT ERROR (2).
        /// </summary>
        internal static string ErrI2 {
            get {
                return ResourceManager.GetString("ErrI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown INPUT ERROR (8).
        /// </summary>
        internal static string ErrI8 {
            get {
                return ResourceManager.GetString("ErrI8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Air Temperature Sensor.
        /// </summary>
        internal static string ErrIAT {
            get {
                return ResourceManager.GetString("ErrIAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Stepper Motor.
        /// </summary>
        internal static string ErrIAV {
            get {
                return ResourceManager.GetString("ErrIAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Regulation.
        /// </summary>
        internal static string ErrIdleReg {
            get {
                return ResourceManager.GetString("ErrIdleReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector.
        /// </summary>
        internal static string ErrInj {
            get {
                return ResourceManager.GetString("ErrInj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injectors (group 1).
        /// </summary>
        internal static string ErrInj1 {
            get {
                return ResourceManager.GetString("ErrInj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injectors (group 2).
        /// </summary>
        internal static string ErrInj2 {
            get {
                return ResourceManager.GetString("ErrInj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injectors.
        /// </summary>
        internal static string ErrInjs {
            get {
                return ResourceManager.GetString("ErrInjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Key Code Error.
        /// </summary>
        internal static string ErrKeyCode {
            get {
                return ResourceManager.GetString("ErrKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Knocking sensor.
        /// </summary>
        internal static string ErrKnock {
            get {
                return ResourceManager.GetString("ErrKnock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Knocking Sensor.
        /// </summary>
        internal static string ErrKnockS {
            get {
                return ResourceManager.GetString("ErrKnockS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lambda Sensor.
        /// </summary>
        internal static string ErrLambda {
            get {
                return ResourceManager.GetString("ErrLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Code Received or Link Down.
        /// </summary>
        internal static string ErrLinkDown {
            get {
                return ResourceManager.GetString("ErrLinkDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MAP Sensor.
        /// </summary>
        internal static string ErrMAP {
            get {
                return ResourceManager.GetString("ErrMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MIL Lamp.
        /// </summary>
        internal static string ErrMIL {
            get {
                return ResourceManager.GetString("ErrMIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mixture ratio.
        /// </summary>
        internal static string ErrMixRatio {
            get {
                return ResourceManager.GetString("ErrMixRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Neutral/drive signal.
        /// </summary>
        internal static string ErrNeutralGear {
            get {
                return ResourceManager.GetString("ErrNeutralGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ECU not synchronized with CODE.
        /// </summary>
        internal static string ErrNoSync {
            get {
                return ResourceManager.GetString("ErrNoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknkown OUTPUT Error (1a).
        /// </summary>
        internal static string ErrO1a {
            get {
                return ResourceManager.GetString("ErrO1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknkown OUTPUT Error (2a).
        /// </summary>
        internal static string ErrO2a {
            get {
                return ResourceManager.GetString("ErrO2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknkown OUTPUT Error (3a).
        /// </summary>
        internal static string ErrO3a {
            get {
                return ResourceManager.GetString("ErrO3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknkown OUTPUT Error (4a).
        /// </summary>
        internal static string ErrO4a {
            get {
                return ResourceManager.GetString("ErrO4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ERRORS:.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RAM.
        /// </summary>
        internal static string ErrRAM {
            get {
                return ResourceManager.GetString("ErrRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ROM.
        /// </summary>
        internal static string ErrROM {
            get {
                return ResourceManager.GetString("ErrROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TDC/RPM Sensor.
        /// </summary>
        internal static string ErrRPMSens {
            get {
                return ResourceManager.GetString("ErrRPMSens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SMOT sensor.
        /// </summary>
        internal static string ErrSMOT {
            get {
                return ResourceManager.GetString("ErrSMOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signal Panel Sequence.
        /// </summary>
        internal static string ErrSPS {
            get {
                return ResourceManager.GetString("ErrSPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ECU Disallowed to Start Engine.
        /// </summary>
        internal static string ErrStartDis {
            get {
                return ResourceManager.GetString("ErrStartDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Throttle Position Sensor.
        /// </summary>
        internal static string ErrTPS {
            get {
                return ResourceManager.GetString("ErrTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ECU has received the &apos;Universal Code&apos;.
        /// </summary>
        internal static string ErrUniCode {
            get {
                return ResourceManager.GetString("ErrUniCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incorrect or Unrecognized Code.
        /// </summary>
        internal static string ErrUnrCode {
            get {
                return ResourceManager.GetString("ErrUnrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAE blocked open or closed.
        /// </summary>
        internal static string ErrVAE {
            get {
                return ResourceManager.GetString("ErrVAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waste Gate.
        /// </summary>
        internal static string ErrWasteG {
            get {
                return ResourceManager.GetString("ErrWasteG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Press [Esc] to Cancel.
        /// </summary>
        internal static string EscCancel {
            get {
                return ResourceManager.GetString("EscCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EVAP Valve.
        /// </summary>
        internal static string EVAP {
            get {
                return ResourceManager.GetString("EVAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [F10] Connect.
        /// </summary>
        internal static string F10_Connect {
            get {
                return ResourceManager.GetString("F10_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [F10] Disconnect.
        /// </summary>
        internal static string F10_Disconnect {
            get {
                return ResourceManager.GetString("F10_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Press [F11] to confirm.
        /// </summary>
        internal static string F11_Confirm {
            get {
                return ResourceManager.GetString("F11_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Self-Adaptation Activated in EEPROM.
        /// </summary>
        internal static string FABEEAT {
            get {
                return ResourceManager.GetString("FABEEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Self-Adaptation Activated in EEPROM.
        /// </summary>
        internal static string FABEEATi {
            get {
                return ResourceManager.GetString("FABEEATi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Self-Adaptation Activated in EPROM.
        /// </summary>
        internal static string FABEPAT {
            get {
                return ResourceManager.GetString("FABEPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Self-Adaptation Activated in EPROM.
        /// </summary>
        internal static string FABEPATi {
            get {
                return ResourceManager.GetString("FABEPATi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FAILED.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lambda in Closed Loop.
        /// </summary>
        internal static string FLGSMA {
            get {
                return ResourceManager.GetString("FLGSMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fuel Pump Relay.
        /// </summary>
        internal static string FuelPump {
            get {
                return ResourceManager.GetString("FuelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generic Relay.
        /// </summary>
        internal static string GenericRelay {
            get {
                return ResourceManager.GetString("GenericRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INIT. FAIL.
        /// </summary>
        internal static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injection Timing Angle.
        /// </summary>
        internal static string INJ_AVA {
            get {
                return ResourceManager.GetString("INJ_AVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector.
        /// </summary>
        internal static string Injector {
            get {
                return ResourceManager.GetString("Injector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector 1.
        /// </summary>
        internal static string Injector1 {
            get {
                return ResourceManager.GetString("Injector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector 2.
        /// </summary>
        internal static string Injector2 {
            get {
                return ResourceManager.GetString("Injector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector 3.
        /// </summary>
        internal static string Injector3 {
            get {
                return ResourceManager.GetString("Injector3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injector 4.
        /// </summary>
        internal static string Injector4 {
            get {
                return ResourceManager.GetString("Injector4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injectors.
        /// </summary>
        internal static string Injectors {
            get {
                return ResourceManager.GetString("Injectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PENDING....
        /// </summary>
        internal static string InProceed {
            get {
                return ResourceManager.GetString("InProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Stepper Integral Gain.
        /// </summary>
        internal static string INTEGR {
            get {
                return ResourceManager.GetString("INTEGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lambda Probe Correction.
        /// </summary>
        internal static string K_O2 {
            get {
                return ResourceManager.GetString("K_O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lambda Probe Voltage.
        /// </summary>
        internal static string K_O2_RAW {
            get {
                return ResourceManager.GetString("K_O2_RAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [stringa troncata]&quot;;.
        /// </summary>
        internal static string lang_it {
            get {
                return ResourceManager.GetString("lang_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max LEAN.
        /// </summary>
        internal static string MaxLEAN {
            get {
                return ResourceManager.GetString("MaxLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max RICH.
        /// </summary>
        internal static string MaxRICH {
            get {
                return ResourceManager.GetString("MaxRICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MIL Lamp.
        /// </summary>
        internal static string MIL {
            get {
                return ResourceManager.GetString("MIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manifold Absolute Pressure.
        /// </summary>
        internal static string MP2_MP8 {
            get {
                return ResourceManager.GetString("MP2_MP8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manifold Absolute Pressure (TURBO).
        /// </summary>
        internal static string MP2_MP8t {
            get {
                return ResourceManager.GetString("MP2_MP8t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Air Temperature.
        /// </summary>
        internal static string MT_AIR_L {
            get {
                return ResourceManager.GetString("MT_AIR_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Water Temperature.
        /// </summary>
        internal static string MT_EAU_L {
            get {
                return ResourceManager.GetString("MT_EAU_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Air.
        /// </summary>
        internal static string NoAir {
            get {
                return ResourceManager.GetString("NoAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 1.
        /// </summary>
        internal static string OFFSET1 {
            get {
                return ResourceManager.GetString("OFFSET1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 2.
        /// </summary>
        internal static string OFFSET2 {
            get {
                return ResourceManager.GetString("OFFSET2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 3.
        /// </summary>
        internal static string OFFSET3 {
            get {
                return ResourceManager.GetString("OFFSET3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 4.
        /// </summary>
        internal static string OFFSET4 {
            get {
                return ResourceManager.GetString("OFFSET4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 5.
        /// </summary>
        internal static string OFFSET5 {
            get {
                return ResourceManager.GetString("OFFSET5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ ZONE 6.
        /// </summary>
        internal static string OFFSET6 {
            get {
                return ResourceManager.GetString("OFFSET6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autocalibration Injection Offset @ IDLE.
        /// </summary>
        internal static string OFFSETm {
            get {
                return ResourceManager.GetString("OFFSETm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Engine Speed Offset.
        /// </summary>
        internal static string OFNNTR {
            get {
                return ResourceManager.GetString("OFNNTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Circuit.
        /// </summary>
        internal static string OpenCircuit {
            get {
                return ResourceManager.GetString("OpenCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Over Boost.
        /// </summary>
        internal static string OverB {
            get {
                return ResourceManager.GetString("OverB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PARAMETERS:.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PASSED.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Engine Speed.
        /// </summary>
        internal static string PERIODE {
            get {
                return ResourceManager.GetString("PERIODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Press [F10] to close connection or [F12] to try to reconnect.
        /// </summary>
        internal static string Press_F10 {
            get {
                return ResourceManager.GetString("Press_F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previously selected port {0} is no longer available. Please select another port..
        /// </summary>
        internal static string PreviouslySelectedPort {
            get {
                return ResourceManager.GetString("PreviouslySelectedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Stepper Proportional Gain.
        /// </summary>
        internal static string PROP {
            get {
                return ResourceManager.GetString("PROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a REV Meter.
        /// </summary>
        internal static string REVmeter {
            get {
                return ResourceManager.GetString("REVmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RPM.
        /// </summary>
        internal static string rpm {
            get {
                return ResourceManager.GetString("rpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Short to GND.
        /// </summary>
        internal static string ShortToGND {
            get {
                return ResourceManager.GetString("ShortToGND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Short to GND/Open.
        /// </summary>
        internal static string ShortToGNDorOpen {
            get {
                return ResourceManager.GetString("ShortToGNDorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Short to +Vcc.
        /// </summary>
        internal static string ShortToVcc {
            get {
                return ResourceManager.GetString("ShortToVcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SIMULATION MODE!!!.
        /// </summary>
        internal static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ABS active.
        /// </summary>
        internal static string StaABSON {
            get {
                return ResourceManager.GetString("StaABSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignition Advance Decrased for Knocking.
        /// </summary>
        internal static string StaAdvDecr {
            get {
                return ResourceManager.GetString("StaAdvDecr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Air Conditioner ON.
        /// </summary>
        internal static string StaAirCoON {
            get {
                return ResourceManager.GetString("StaAirCoON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lambda Sensor in Closed Loop.
        /// </summary>
        internal static string StaClLoop {
            get {
                return ResourceManager.GetString("StaClLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Engine Running.
        /// </summary>
        internal static string StaEngRun {
            get {
                return ResourceManager.GetString("StaEngRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gear Engaged.
        /// </summary>
        internal static string StaGearEng {
            get {
                return ResourceManager.GetString("StaGearEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mixture AutoCalibration ENABLED.
        /// </summary>
        internal static string StaMixACOK {
            get {
                return ResourceManager.GetString("StaMixACOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Power Latch Line OK.
        /// </summary>
        internal static string StaPLatchOK {
            get {
                return ResourceManager.GetString("StaPLatchOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sensor Signals OK.
        /// </summary>
        internal static string StaSensOK {
            get {
                return ResourceManager.GetString("StaSensOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signal panel OK.
        /// </summary>
        internal static string StaSigPanOK {
            get {
                return ResourceManager.GetString("StaSigPanOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stepper AutoCalibration ENABLED.
        /// </summary>
        internal static string StaStepACOK {
            get {
                return ResourceManager.GetString("StaStepACOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Throttle at Min/Max.
        /// </summary>
        internal static string StaThrMM {
            get {
                return ResourceManager.GetString("StaThrMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAE Self Cleaning underway.
        /// </summary>
        internal static string StaVAESC {
            get {
                return ResourceManager.GetString("StaVAESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stepper motor (idle actuator).
        /// </summary>
        internal static string Stepper {
            get {
                return ResourceManager.GetString("Stepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle stepper autocalibration reset.
        /// </summary>
        internal static string StepReset {
            get {
                return ResourceManager.GetString("StepReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a steps.
        /// </summary>
        internal static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set stepper correction (ALFAFTR).
        /// </summary>
        internal static string StepSet {
            get {
                return ResourceManager.GetString("StepSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [S].
        /// </summary>
        internal static string Sto {
            get {
                return ResourceManager.GetString("Sto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injection Duration.
        /// </summary>
        internal static string T_INJ_AP {
            get {
                return ResourceManager.GetString("T_INJ_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VAE Duty Cycle (Idle Control).
        /// </summary>
        internal static string T_VAE {
            get {
                return ResourceManager.GetString("T_VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If test takes longer than {0}s please turn ignition OFF and close the application!.
        /// </summary>
        internal static string TestDuration {
            get {
                return ResourceManager.GetString("TestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TESTING: {0}....
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Short to GND/+Vcc/Therm.
        /// </summary>
        internal static string Therm {
            get {
                return ResourceManager.GetString("Therm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TIMEOUT.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle idle stepper autocalibration.
        /// </summary>
        internal static string ToggleStepAC {
            get {
                return ResourceManager.GetString("ToggleStepAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle fuel trim autocalibration.
        /// </summary>
        internal static string ToggleTrimAC {
            get {
                return ResourceManager.GetString("ToggleTrimAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Too Much Air.
        /// </summary>
        internal static string TooMuchAir {
            get {
                return ResourceManager.GetString("TooMuchAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trimmer Position.
        /// </summary>
        internal static string TRIMRAM {
            get {
                return ResourceManager.GetString("TRIMRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fuel trim autocalibration reset.
        /// </summary>
        internal static string TrimReset {
            get {
                return ResourceManager.GetString("TrimReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set trimmer position (TRIMRAM).
        /// </summary>
        internal static string TrimSet {
            get {
                return ResourceManager.GetString("TrimSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please turn OFF the ignition....
        /// </summary>
        internal static string TurnOFF {
            get {
                return ResourceManager.GetString("TurnOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string UnknownISO {
            get {
                return ResourceManager.GetString("UnknownISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ECU could not be recognized, please turn OFF the ignition....
        /// </summary>
        internal static string UnrecECU {
            get {
                return ResourceManager.GetString("UnrecECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Battery Voltage.
        /// </summary>
        internal static string V_BATT {
            get {
                return ResourceManager.GetString("V_BATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Idle Control Valve (VAE).
        /// </summary>
        internal static string VAE {
            get {
                return ResourceManager.GetString("VAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [V].
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a YES;;NO.
        /// </summary>
        internal static string yes_no {
            get {
                return ResourceManager.GetString("yes_no", resourceCulture);
            }
        }
    }
}
